version: "3"

networks:
  watcharr:

# To test prod
services:
  watcharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcharr
    networks:
      - watcharr
    ports:
      - 3000:3000
      - 3080:3080
    volumes:
      - ./server/.env:/.env
      - ./container_data:/data
