version: "3"

services:
  watcharr:
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      - ./server/.env:/.env
      - ./container_data:/data
